### PR TITLE
Fix failing low transfers

### LINKED ISSUE #244: Can't transfer low enough funds
I ran into learning that `Transfer` fails when the value being transferred is low enough. So far, the lowest amount I've seen being accepted as 1000.

### PR DESCRIPTION
**Pull request by NunoAlexandre**
Fixes #244 

Change the 'ExistencialDeposit' parameter passed when defining the
runtime. Test that we can transfer any amount within a reasonable range
to cover ourselves from re-introducing this bug again.

### Discussion

It's a shame that `ExistencialDeposit` is used both as the minimum amount required to keep an account open and as a minimum transfer amount. I set it from 500 to 1 but maybe something in between would be better to keep the accounts cleaner.

### CODE REVIEW

File: runtime/src/lib.rs [hunk 1]
```diff
@@ -160,7 +160,9 @@ impl pallet_timestamp::Trait for Runtime {
 }
 
 parameter_types! {
-    pub const ExistentialDeposit: u128 = 500;
+    /// The minimum amount required to keep an account open.
+    /// It also defines the minimum allowed transfer.
```
Comment (geigerzaehler) [inline runtime/src/lib.rs]: I don’t think it is true that this is the minimum transfer amount. I had a look at the code and this is not checked anywhere.

Comment (NunoAlexandre) [reply runtime/src/lib.rs]: Then it does play a role indirectly because I could effectively move the minimum allowed transfer by changing this value. 🤔

Comment (NunoAlexandre) [reply runtime/src/lib.rs]: @geigerzaehler found it:

https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L892

In an older version of the substrate repo I have locally, in the `fn transfer` in the `ballances` it was doing:

``` rust
if would_create && value < T::ExistentialDeposit::get() {
  Err(Error::<T, I>::ExistentialDeposit)?
}
```

Now looking at the latest master, the only close thing I can find is the following, which is different:

https://github.com/paritytech/substrate/blob/dd97b1478b31a4715df7e88a5ebc6664425fb6c6/frame/balances/src/lib.rs#L966-L967


Maybe this was a bug now fixed. Will rebase and see.

Comment (NunoAlexandre) [reply runtime/src/lib.rs]: @geigerzaehler I now got the problem. So, it's not that this value is used as a minimum transfer amount per se, but say that when transferring `x ` amount from account A to account B, if doing so leaves `B` with fewer funds than this `ExistencialDeposit` amount, then it fails. I verified this by _first_ transferring an amount above the `ExistencialDeposit` value and then below, which works, but not the way around. Rephrased the comment.

Comment (geigerzaehler) [reply runtime/src/lib.rs]: Yes, that sounds correct.
