### PR TITLE
Cli/fix leaked abstraction

### LINKED ISSUE #314: Bootstrapping CLI accounts is not working
When using the CLI for the first and no account exists yet it is impossible to create an account. The following command fails

```
$ radicle-registry-cli --tx-author default account generate default
error: Invalid value for '--tx-author <account_name>': Could not find local account named 'default'
```

### PR DESCRIPTION
**Pull request by NunoAlexandre**
Fixes #314 #283 #281 

As explained in #283, have each command define the options that it needs to run.
Done by flattening shared options, one for the network and the other for the transaction-related options.

### CODE REVIEW

File: cli/src/command/account.rs [hunk 1]
```diff
@@ -19,41 +19,45 @@ use super::*;
 use crate::account_storage;
 
 /// Account related commands
-#[derive(StructOpt, Debug, Clone)]
```
Comment (geigerzaehler) [inline cli/src/command/account.rs]: Could we keep the `Debug` implementation. I know it’s not necessary but its intended for debugging after all. It will become very annoying if you want to `println!` a command and you first need to add `Debug` to it and all its constituents.

Comment (NunoAlexandre) [reply cli/src/command/account.rs]: So I had to remove it because `ed25519::Pair` does not implement it, so any type including it won't be able to derive it. A way I see around this is to have the `TxOptions` `author` field be an account name and have each command get the key pair from it, as you suggested in a previous PR. We could have this one as is and I address that change in as separate PR?

**Comment by CodeSandwich** [comment]
I've removed all the `Box`es and it's compiling without any warnings.

**Comment by CodeSandwich** [comment]
Ok, it's a clippy warning. Ugh.

**Comment by NunoAlexandre** [comment]
That is a good observation, @CodeSandwich. I like that more in the given context. @geigerzaehler do you agree?

**Comment by CodeSandwich** [comment]
Maybe we should annotate the whole cli crate, it contains no high performance code or structures and this is going to kick us over and over again.

**Comment by NunoAlexandre** [comment]
@CodeSandwich @geigerzaehler I added `#![allow(clippy::large_enum_variant)]` to the cli `lib.rs` instead of `Box`ing each hurting command. Nothing else to address here.
